// frontend/src/components/Nav/Nav.tsx
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '~/auth';
import { Button, Container } from '~/ui';
import './Nav.scss';

export const Nav = () => {
  const navigate = useNavigate();
  const { user, logout, setUser } = useAuth();

  function handleLogout() {
    logout().then(() => {
      setUser(undefined);
      navigate('/login');
    });
  }

  return (
    <nav className="Nav">
      <Container>
        <div className="Nav__content">
          <Link to="/">
            <h1>FitPulse</h1>
          </Link>
          {user && (
            <Link to="/exercises">
              <Button color="primary" size="sm">
                Exercises
              </Button>
            </Link>
          )}
          <div className="Nav__spacer"></div>
          {user ? (
            <Button color="primary" onClick={handleLogout} size="sm">
              Logout
            </Button>
          ) : (
            <>
              <Link to="/signup">
                <Button color="primary" size="sm">
                  Sign Up
                </Button>
              </Link>
              <Link to="/login">
                <Button color="primary" size="sm" variant="raised">
                  Login
                </Button>
              </Link>
            </>
          )}
        </div>
      </Container>
    </nav>
  );
};

// angular/src/app/components/nav/nav.component.ts
import { AuthService } from '@/app/auth';
import { Component } from '@angular/core';
import { Router, RouterModule } from '@angular/router';

@Component({
  selector: 'app-nav',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './nav.component.html',
  styleUrl: './nav.component.scss',
})
export class NavComponent {
  constructor(
    public auth: AuthService,
    private router: Router,
  ) {}

  public logout() {
    this.auth.logout().subscribe({
      next: () => {
        this.auth.user.set(undefined);
        this.router.navigate(['/login']);
      },
      error: (error) => {
        console.error(error);
      },
    });
  }
}

<div class="nav">
  <div class="pw-container">
    <div class="nav__content">
      <a class="nav__title" [routerLink]="['/']"><h1>FitPulse</h1></a>
      <div class="nav__spacer"></div>
      @if (auth.user()) {
        <button class="pw-button primary raised sm" (click)="logout()">Logout</button>
      } @else {
        <button class="pw-button primary sm" [routerLink]="['/signup']">Sign Up</button>
        <button class="pw-button primary raised sm" [routerLink]="['/login']">Login</button>
      }
    </div>
  </div>
</div>
